### ISSUE TITLE
YAML sequences

### ISSUE THREAD

**Issue by raymondtieu** [jasonmit/ember-intl#325]
Are there any methods to translate YAML sequences? For example translating something of the form:
```
products:
  - product: "Product A"
    productNumber: 1
    price: 10.99
  - product: "Product B"
    productNumber: 7
    price: 16.99
  ...
```
